name: hello action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install -y curl jq
          echo "Dependencies installed"
          echo "curl version: $(curl --version)"
          echo "jq version: $(jq --version)"

      - name: Show current date
        run: date

      - name: Run a one line action
        run: echo "Hello world!"

      - name: Show system information
        run: |
          echo "username ${{ github.actor }}"
          echo "OS ${{ runner.os }}"
          echo "Architecture ${{ runner.arch }}"

  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List files
        run: ls

      - name: list hidden files
        run: ls -a

      - name: Display file on the repository
        run: ls -la